version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: bashboard_db
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "88880000"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
